---

- name: Create data center "site1_datacenter"
  bigip_gtm_datacenter:
    server: "10.1.10.13"
    name: "site1_datacenter"
    location: "55 Hudson"
  delegate_to: localhost

- name: Create data center "site2_datacenter"
  bigip_gtm_datacenter:
    server: "10.1.10.13"
    name: "site2_datacenter"
    location: "151 Front"
  delegate_to: localhost


#- name: "Create a Server"
##  uri:
##    url: "https://10.1.10.13/mgmt/tm/gtm/global-settings/general"
##    method: "PATCH"
##    validate_certs: no
##    username: "admin"
##    password: "admin"
##    body_format: "json"
##    force_basic_auth: no
##    body:
##      synchronization: "yes"
##      synchronizationGroupName: "EXAMPLE_group"
##      synchronizeZoneFiles: "yes"
##  delegate_to: localhost
#
#
#

- name: Get an API token
  uri:
    url: "https://10.1.10.13/mgmt/shared/authn/login"
    method: POST
    body: |
      {
        "username": "admin",
        "password": "admin",
        "loginProviderName": "tmos"
      }
    status_code: 200
    body_format: json
    validate_certs: "no"
  register: auth

- name: Check for gtm pool www.example.com_pool
  uri:
    url: "https://10.1.10.13/mgmt/tm/gtm/pool/a/~Common~www.example.com_pool"
    method: GET
    headers:
      X-F5-Auth-Token: "{{ auth['json']['token']['name'] }}"
    status_code: [200,404]
    validate_certs: "no"
  register: pool

- name: Create a gtm pool
  uri:
    url: "https://10.1.10.13/mgmt/tm/gtm/pool/a"
    method: POST
    body: |
      {
        "name": "www.example.com_pool",
        "partition": "Common",
      }
    headers:
      X-F5-Auth-Token: "{{ auth['json']['token']['name'] }}"
    status_code: 200
    validate_certs: "no"
    body_format: json
  when: pool.status == 404

- name: Check for a pool member
  uri:
    url: "https://10.1.10.13/mgmt/tm/gtm/pool/a/~Common~www.example.com_pool/members/~Common~1.1.1.1:80"
    method: GET
    headers:
      X-F5-Auth-Token: "{{ auth['json']['token']['name'] }}"
    status_code: 200, 404
    validate_certs: "no"
  register: pool_member

- name: Create a pool member
  uri:
    url: "https://10.1.10.13/mgmt/tm/gtm/pool/a/~Common~www.example.com_pool/members"
    method: POST
    body: |
      {
        "name": "1.1.1.1:80",
        "address": "1.1.1.1",
        "partition": "Common"
      }
    headers:
      X-F5-Auth-Token: "{{ auth['json']['token']['name'] }}"
    status_code: 200
    validate_certs: "no"
    body_format: json
  when: pool_member.status == 404

- name: Save config to disk
  uri:
    url: "https://10.1.10.13/mgmt/tm/sys/config"
    method: POST
    body: |
      {
        "command":"save"
      }
    headers:
      X-F5-Auth-Token: "{{ auth['json']['token']['name'] }}"
    status_code: 200
    body_format: json
    validate_certs: "no"

- name: Destroy an API token
  uri:
    url: "https://10.1.10.13/mgmt/shared/authz/tokens/{{ auth['json']['token']['name'] }}"
    method: DELETE
    headers:
      X-F5-Auth-Token: "{{ auth['json']['token']['name'] }}"
    status_code: 200
    validate_certs: "no"
  register: auth

...
