---

- name: Create isp1.site1 vlan
  bigip_provision:
  delegate_to: localhost

  bigip_vlan:
    name: "isp1_vlan"
    untagged_interfaces: "1.1"
    description: "Service Provider 1 in Site 1"
    server: "{{ inventory_hostname }}"
    password: "admin"
    user: admin
    validate_certs: no
    tag: "4"
  delegate_to: localhost

...
