- name: Send notification message via Slack all options
  slack:
    token: T8BTH8LP9/BB6HC5JBF/XH659Ygh28NHkjYdq2GhUdrf
    msg: '{{ inventory_hostname }} completed'
    channel: #general
    username: 'Ansible on {{ inventory_hostname }}'
    icon_url: https://upload.wikimedia.org/wikipedia/commons/2/24/Ansible_logo.svg
    link_names: 0
    parse: 'none'
  delegate_to: localhost

...
