---

- name: Create isp2.site2 vlan
  bigip_provision:
  delegate_to: localhost

  bigip_vlan:
    name: "isp2_vlan"
    untagged_interfaces: "1.3"
    description: "Service Provider 1 in Site 1"
    server: "{{ inventory_hostname }}"
    password: "admin"
    user: admin
    validate_certs: no
    tag: "7"
  delegate_to: localhost

...
