---
- name: GSLB configuration
  hosts: 10.1.10.13
  gather_facts: false
  vars:
    setup_user: "admin"
    setup_pass: "admin"
  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: admin
    F5_PASSWORD: admin
    F5_SERVER_PORT: 443
    F5_VALIDATE_CERTS: no

  tasks:

  - name: 
    include_role:
      name: bigip_gtm

...
